### ISSUE TITLE
Warning: command 'latex-workshop.onEnterKey' not found

### ISSUE THREAD

**Issue by Lutalli** [James-Yu/LaTeX-Workshop#1193]
I was trying to use the vscode extension _LaTeX Workshop_. As soon as I pressed the `Enter` button, in order to start a new line, vscode warned me **command 'latex-workshop.onEnterKey' not found**.
What's going on?

```
vscode version: 1.31.0
extension version: 6.0.0
```

Thanks

\-

This problem (v6.0.0) is simply because there was something wrong with my environment variable `TEMP`. But version 6.1.0 has the same issue, for another unknown reason (see the comments below).

Also see https://github.com/Microsoft/vscode/issues/70055.

**Comment by jlelong** [comment]
You probably have something wring with your installation of _LaTeX Workshop_. Close vscode and remove `.vscode/extensions/james-yu.latex-workshop-6.0.0`. Then reinstall the extension from the [marketplace](https://marketplace.visualstudio.com/items/James-Yu.latex-workshop).

**Comment by Lutalli** [comment]
Thx for your reply!
However the problem remains unsolved. By the way, I can't download all the extensions online, I have to install them from VSIX instead (offline) - could that be the reason?

**Comment by jlelong** [comment]
I have tried the VSIX installation way and it does work. You must have something else wrong with your installation.
Can you try to disable all other extensions and see if the problem persists? Can you post the logs from the extension?

**Comment by Lutalli** [comment]
It persists.
Where can I find the logs? (sorry but I'm new to this) vscode only said:
![image](https://user-images.githubusercontent.com/47910890/53285012-76d7ff80-3796-11e9-9670-04de576c326e.png)
in the keybindings:
![image](https://user-images.githubusercontent.com/47910890/53285042-c74f5d00-3796-11e9-8f36-8de82b7ff569.png)

**Comment by jlelong** [comment]
From the left _TeX_ Panel, View log messages -> View LaTeX Workshop extension.
The logs will show up in the bottom panel.

<img width="313" alt="capture d ecran 2019-02-23 a 16 53 32" src="https://user-images.githubusercontent.com/2910140/53288676-96b5f600-378b-11e9-98fa-cf6d8a31724a.png">

**Comment by Lutalli** [comment]
There isn't even a _TeX_ panel.
![image](https://user-images.githubusercontent.com/47910890/53293915-ecd07b00-3817-11e9-9b64-a9ac332650ad.png)

**Comment by jlelong** [comment]
The TeX panel only shows up when editing a `.tex` file.

**Comment by Lutalli** [comment]
I still can't see the panel when I have already opened a `.tex` file.

I have tried disabling all other extensions and it persists.

**Comment by jlelong** [comment]
There is something wrong with some installation. With no hint on the problem, my advice is to remove vscode and all the extensions completely, ie remove
- Windows: `%USER%\.vscode\extensions` or `%USERPROFILE%\.vscode\extensions`
- macOS or Linux: `~/.vscode/extensions`

You may need to remove also all vscode settings
- Windows `%APPDATA%\Code\User\settings.json`
- macOS `~/Library/Application Support/Code/User/settings.json`
- Linux `~/.config/Code/User/settings.json`

**Comment by Lutalli** [comment]
I tried that way, but again, that didn't work!
And I found that many of the commands couldn't be found, such as all of these:
![image](https://user-images.githubusercontent.com/47910890/53643108-32ed6a80-3c6e-11e9-8c11-4ecae2b9dd07.png)
![image](https://user-images.githubusercontent.com/47910890/53643061-12bdab80-3c6e-11e9-9a78-ef2f60ee082a.png)

**Comment by jlelong** [comment]
You mean that you removed all the extensions and vscode. Then, after only reinstalling LaTeX-Workshop, you still have all these unknown commands. If so, there is definitely something wrong on your computer and I am sorry but I cannot see how we can help you further.

**Comment by Lutalli** [comment]
Well. Anyway, thanks for your so much help!

**Comment by Rigbin** [comment]
@Lutalli, I had the same issue today (started writing on a .tex-file after a view months) and had solved it by installing an older version of the LaTeX-Workshop extension. Maybe this could also help you.
![vscode_latex-workshop_older-version](https://user-images.githubusercontent.com/24607675/53780366-6d703500-3f04-11e9-8408-04135dc64905.png)

For me, it works with the Version `5.21.0`. I work with the current VSCode Version `1.31.1` on a Linux System.

**Comment by Sinnlosvoll** [comment]
I can confirm that an older version seems to be the only way to get latex workshop to work, as 6.1.0 just does not find any command with vscode 1.31.1 on windows. 
Downgrading to 6.0.0 works again.
There is also nothing corresponding to latex workshop in the settings file, that is not telemetry or color scheme related.
@jlelong please reopen this issue, as it is not resolved.

**Comment by James-Yu** [comment]
It's not related to the extension. Follow the previous delete-and-reinstall instructions. If the problem persists, please open an issue at vscode's repo.

**Comment by fknop** [comment]
Just had the same issue with 6.1.0, I downgraded to 6.0.0 as @Sinnlosvoll said and it works now.

**Comment by GaloisGecko** [comment]
I as well had the same issue with 6.1.0 and vscode 1.31.1 on windows, Also for me, downgrading to 6.0.0 as @Sinnlosvoll said works.

**Comment by HamOnBry** [comment]
Came across the same issue this morning. Downgrading to 6.0.0 as @Sinnlosvoll stated also solved the issue.

**Comment by tim-kilian** [comment]
Can someone fix this for the newest version? Pretty annoying

**Comment by jlelong** [comment]
As @James-Yu said above, we cannot reproduce the issue and we haven't changed anything related to this. It seems to an issue in the upgrade process inside vscode. If the delete and reinstall steps do not help, fill an issue on vscode's repo.

**Comment by tim-kilian** [comment]
Maybe its something related to Windows 7. I just tried it on Windows 10 and it worked (v6.1.0).

**Comment by HamOnBry** [comment]
I'm on Ubuntu 18.10 and had the issue so I doubt it's related to Windows 7 specifically

**Comment by wrvsrx** [comment]
The issue exists in my Windows 10, so it might not related to Windows 7. By the way, it doesn't work to downgrade to 6.0.0 for me.

**Comment by bauersimon** [comment]
Same problem - same solution! Downgraded to `5.21.0` and it's working again (Windows 10).

**Comment by eeshiken** [comment]
Issue existed on MacOS
- Downgrading to `Latex Workshop 6.0.0` fixed the issue
- Upgrading to `VSCode 1.32.0` + `Latex Workshop 6.1.0` also fixed the issue.

**Comment by hkawash** [comment]
The same issue exists on my Windows 10, VS code 1.31.1, latex-workshop v6.1.0. Downgrading to v6.0.0 solved the issue. Upgrading to v6.1.0 again caused the issue but was solved after downgrading again.

**Comment by tim-kilian** [comment]
> 
> 
> Issue existed on MacOS
> 
>     * Downgrading to `Latex Workshop 6.0.0` fixed the issue
> 
>     * Upgrading to `VSCode 1.32.0` + `Latex Workshop 6.1.0` also fixed the issue.

 `VSCode 1.32.0` + `Latex Workshop 6.1.0`  is still not working for me.

**Comment by tamuratak** [comment]
Please uninstall VSCode and remove the user data dir and settings of VSCode. Remove the dir of extensions. Reinstall VSCode and LaTeX Workshop. Then, check that you still see this issue.

user data dir

- Windows: C:\Users\USERNAME\AppData\Roaming\Code
- Mac: ~/Library/Application Support/Code
- Linux: ~/.config/Code

extensions dir

- Windows: C:\Users\USERNAME\\.vscode
- Mac: ~/.vscode
- Linux: ~/.vscode

If you still see this issue, please do the followings.

1. Open the command palette.
2. Enter `Developer: Toggle Developer Tools` and press enter.
3. Show us messages in the console.

![2018-11-27 20 42 47](https://user-images.githubusercontent.com/10665499/49079823-0a2b9280-f285-11e8-93ee-421fc1870ae8.png)

![2018-11-27 20 43 43](https://user-images.githubusercontent.com/10665499/49079859-29c2bb00-f285-11e8-9446-1be80c11df01.png)

![2018-11-27 20 44 45](https://user-images.githubusercontent.com/10665499/49080094-df8e0980-f285-11e8-9111-2d02affc45f6.png)

Thank you for your cooperation.

**Comment by Lutalli** [comment]
- Thank guys for your replies tho I have closed this issue!

- @tamuratak Remove-Reinstall way always didn't work. In console:
![image](https://user-images.githubusercontent.com/47910890/54028682-d5629c00-41e0-11e9-94e2-8708a37b5cff.png)


- An older version may be a true way, but for me there is another problem - as what I said before,

>  ... I can't download all the extensions online, I have to install them from VSIX instead (offline) ...

then how to install an older VSIX?

- I'll open a new issue at vscode's repo soon.

**Comment by tamuratak** [comment]
The environment variable `TMP`, `TEMP`, or `TMPDIR` on your PC is set incorrectly. `TMP` is not `PATH`. `TMP` must include only one dir.

**Comment by Lutalli** [comment]
@tamuratak There's nothing wrong with `TMP` for sure, it includes only 1 dir.

**Comment by tamuratak** [comment]
So, what is `C:\Users\admin\AppData\Local\Programs\Common\Python\343` in your log?

**Comment by tamuratak** [comment]
Please see [link](https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10). Show us  all the environment variables on your PC.

**Comment by Lutalli** [comment]
@tamuratak Sorry I didn't notice `TEMP`. My `TEMP` was:

`%USERPROFILE%\AppData\Local\Temp;C:\Users\admin\AppData\Local\Programs\Common\Python\343;`

Now I delete the python path, and v6.0.0 works well. It let me use the old version successfully (but there's still the new version problem).

Also, the `TEMP` caused some other issues on my computer before (**I can download the extensions online now!**), they are all fixed.

Thanks a bunch!

**Comment by tamuratak** [comment]
Good. You're welcome.

**Comment by tamuratak** [comment]
Anybody else? If you want to solve your issue, please show us your console log as above.  Just 👍 does not solve any issue.  

If you have solved your issue, please tell us. Then, we can close this issue.

Thank you for your cooperation.

**Comment by Lutalli** [comment]
I have already resolved my issue, and I can use v6.1.0, but it seems that some other people can't - do I close this issue?

**Comment by jlelong** [comment]
Let's close this one as the original problem is solved.
Open a new issue if you have trouble using the latest release.

**Comment by tim-kilian** [comment]
For me it was a non working `pdflatex --version` command  working fine now for me

**Comment by salvadord** [comment]
I had the same issue in a Mac OS 10.12.6 and fixed by installing a previous version of latex-workshop (6.0.0)

**Comment by tamuratak** [comment]
@salvadord, if you wanto to solve your problem, please open a new issue. Show us your console log as above in the issue.

**Comment by Sinnlosvoll** [comment]
@Lutalli I see you mentioning python..
Before this happened I also installed a python extension for vs code, but didn't think it would matter, especially since I removed it, before reinstalling vs code and the problem persisted. So I assume the python extension installation messed up the %TEMP% path.

Anyway, the problem is gone now with vs code 1.32.3 and plugin version 6.2.2.
