### ISSUE TITLE
Latex Workshop cannot recompile after first compilation, output pdf file is locked

### ISSUE THREAD

**Issue by lucblassel** [James-Yu/LaTeX-Workshop#1662]
**Disable all the other extensions except for LaTeX Workshop, and check that you still see this issue.**

You still see this issue?: Yes

**If your issue is with compiling a document (not having to do with finding the root file of a project), check first that you can compile manually.**  
I can compile manually by calling the docker container with the following command:  
`docker run -w "$(pwd)" -v "$(pwd):$(pwd)" blang/latex:ctanfull latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf filename`

**Describe the bug [Required]**
After the first successful build which, when re-building changes made to the document, an error is shown sating that the .pdf file is locked, and the compiler is not called. Any additional calls to the BUILD command is unsuccessful and doesn't show any additional error messages in the notifications. 

**To Reproduce**
1. Create a new folder and a new  dummy .tex document and save to build:
````tex
\documentclass{article}
\begin{document}
    Hello World.
\end{document}
````
2. Modify document and save again additional times. 
3. After the first modification, build will fail with the following error in the notification tray: `/home/lblassel/latex_workshop_test/latex.pdf is locked. Is it opened in other applications?`
4. Any subsequent modifications and saves to build fail without notification, and the compiler is not even called.

**Expected behavior**
The tex document is recompiled and the changes appear in the updated pdf file.

**Logs [Required]**

<details>
<summary>LaTeX Workshop Output [Required]</summary>

````
[13:57:02] Initializing LaTeX Workshop.
[13:57:02] Creating LaTeX Workshop http and websocket server.
[13:57:03] LaTeX Workshop initialized.
[13:57:03] Found root file from active editor: /home/lblassel/latex_workshop_test/latex.tex
[13:57:03] Root file changed from: undefined to /home/lblassel/latex_workshop_test/latex.tex. Find all dependencies.
[13:57:03] Instantiating a new file watcher for /home/lblassel/latex_workshop_test/latex.tex
[13:57:03] Creating file watcher for .bib files.
[13:57:03] Parsing /home/lblassel/latex_workshop_test/latex.tex
[13:57:03] Server created on 127.0.0.1:44644
[13:57:03] Adding /home/lblassel/latex_workshop_test/latex.tex to file watcher.
[13:57:03] Snippet data loaded.
[13:57:03] LaTeX Workshop version: 8.1.0
[13:57:14] Found root file from active editor: /home/lblassel/latex_workshop_test/latex.tex
[13:57:14] Root file remains unchanged from: /home/lblassel/latex_workshop_test/latex.tex.
[13:57:15] Parsing /home/lblassel/latex_workshop_test/latex.tex
[13:57:15] File watcher: responding to change in /home/lblassel/latex_workshop_test/latex.tex
[13:57:15] /home/lblassel/latex_workshop_test/latex.tex changed. Auto build project.
[13:57:15] BUILD command invoked.
[13:57:15] Building root file: /home/lblassel/latex_workshop_test/latex.tex
[13:57:15] Build root file /home/lblassel/latex_workshop_test/latex.tex
[13:57:15] Recipe step 1: /home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/scripts/latexmk, -synctex=1,-interaction=nonstopmode,-file-line-error,-pdf,-outdir=./,latex
[13:57:15] LaTeX build process spawned. PID: 23375.
[13:57:18] LaTeX log parsed with 0 messages.
[13:57:18] Recipe of length 1 finished. PID: 23375.
[13:57:18] Successfully built /home/lblassel/latex_workshop_test/latex.tex.
[13:57:18] No PDF viewer connected for /home/lblassel/latex_workshop_test/latex.pdf
[13:57:23] VIEW command invoked with mode: file:///home/lblassel/latex_workshop_test/latex.tex.
[13:57:23] Found root file from active editor: /home/lblassel/latex_workshop_test/latex.tex
[13:57:23] Root file remains unchanged from: /home/lblassel/latex_workshop_test/latex.tex.
[13:57:23] Serving PDF file at http://localhost:44644/viewer.html?file=pdf..JTJGaG9tZSUyRmxibGFzc2VsJTJGbGF0ZXhfd29ya3Nob3BfdGVzdCUyRmxhdGV4LnBkZg
[13:57:23] The encoded path is /home/lblassel/latex_workshop_test/latex.pdf
[13:57:23] Open PDF tab for /home/lblassel/latex_workshop_test/latex.pdf
[13:57:24] Handle data type: open
[13:57:24] Found root file from active editor: /home/lblassel/latex_workshop_test/latex.tex
[13:57:24] Root file remains unchanged from: /home/lblassel/latex_workshop_test/latex.tex.
[13:57:24] Preview PDF file: /home/lblassel/latex_workshop_test/latex.pdf
[13:57:24] Handle data type: loaded
[13:57:27] Handle data type: close
[13:57:37] Parsing /home/lblassel/latex_workshop_test/latex.tex
[13:57:37] File watcher: responding to change in /home/lblassel/latex_workshop_test/latex.tex
[13:57:37] /home/lblassel/latex_workshop_test/latex.tex changed. Auto build project.
[13:57:37] BUILD command invoked.
[13:57:37] Building root file: /home/lblassel/latex_workshop_test/latex.tex
[13:57:37] Output PDF /home/lblassel/latex_workshop_test/latex.pdf is locked.
[13:57:56] Parsing /home/lblassel/latex_workshop_test/latex.tex
[13:57:56] File watcher: responding to change in /home/lblassel/latex_workshop_test/latex.tex
[13:57:56] /home/lblassel/latex_workshop_test/latex.tex changed. Auto build project.
[13:57:56] BUILD command invoked.
[13:57:56] Building root file: /home/lblassel/latex_workshop_test/latex.tex
[13:58:14] Found root file from active editor: /home/lblassel/latex_workshop_test/latex.tex
[13:58:14] Root file remains unchanged from: /home/lblassel/latex_workshop_test/latex.tex.
[13:58:18] Parsing /home/lblassel/latex_workshop_test/latex.tex
[13:58:18] File watcher: responding to change in /home/lblassel/latex_workshop_test/latex.tex
[13:58:18] /home/lblassel/latex_workshop_test/latex.tex changed. Auto build project.
[13:58:18] BUILD command invoked.
[13:58:18] Building root file: /home/lblassel/latex_workshop_test/latex.tex
[13:58:18] Another LaTeX build processing is already waiting for the current LaTeX build to finish. Exit.
````
</details>

<details>
<summary>Developer Tools Console [Required]</summary>

````  
[Extension Host] debugger listening on port 53636
console.ts:137 [Extension Host] rejected promise not handled within 1 second: MissingPDFException: Missing PDF "/home/lblassel/latex_workshop_test/latex.pdf".
t.log @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: 	at MissingPDFExceptionClosure (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:686:35)	at Object._typeof (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:689:2)	at __w_pdfjs_require__ (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:52:30)	at Object.defineProperty.value (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:129:23)	at __w_pdfjs_require__ (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:52:30)	at pdfjsVersion (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:116:18)	at /home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:119:10	at webpackUniversalModuleDefinition (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:25:20)	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:32:3)	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:23600:3)	at Module._compile (internal/modules/cjs/loader.js:693:30)	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)	at Module.load (internal/modules/cjs/loader.js:602:32)	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)	at Function.Module._load (internal/modules/cjs/loader.js:533:3)	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)	at Module.require (internal/modules/cjs/loader.js:640:17)	at require (internal/modules/cjs/helpers.js:20:18)	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/out/src/components/builder.js:8:18)	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/out/src/components/builder.js:478:3)	at Module._compile (internal/modules/cjs/loader.js:693:30)	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)	at Module.load (internal/modules/cjs/loader.js:602:32)	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)	at Function.Module._load (internal/modules/cjs/loader.js:533:3)	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)	at Module.require (internal/modules/cjs/loader.js:640:17)	at require (internal/modules/cjs/helpers.js:20:18)	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/out/src/main.js:11:19)	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/out/src/main.js:417:3)	at Module._compile (internal/modules/cjs/loader.js:693:30)	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)	at Module.load (internal/modules/cjs/loader.js:602:32)	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)	at Function.Module._load (internal/modules/cjs/loader.js:533:3)	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)	at Module.require (internal/modules/cjs/loader.js:640:17)	at require (internal/modules/cjs/helpers.js:20:18)	at Function.i [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:31:639)	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:60	at I._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:168)	at I._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:762:6)	at I.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:758:868)	at Generator.next (<anonymous>)	at n (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:979)	at new Promise (<anonymous>)	at n (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:756)	at Object.actualActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:758:570)	at p._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:144)	at define._activateExtensions.r.length.Promise.all.s.map.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:814)	at Array.map (<anonymous>)	at p._activateExtensions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:802)	at p.activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:494:635)	at I._activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:680)	at define.$activateByEvent._readyToRunExtensions.wait.then.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:769:470)
t.log @ console.ts:137
log.ts:173   ERR Missing PDF "/home/lblassel/latex_workshop_test/latex.pdf".: Error: 
	at MissingPDFExceptionClosure (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:686:35)
	at Object._typeof (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:689:2)
	at __w_pdfjs_require__ (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:52:30)
	at Object.defineProperty.value (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:129:23)
	at __w_pdfjs_require__ (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:52:30)
	at pdfjsVersion (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:116:18)
	at /home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:119:10
	at webpackUniversalModuleDefinition (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:25:20)
	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:32:3)
	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/node_modules/pdfjs-dist/build/pdf.js:23600:3)
	at Module._compile (internal/modules/cjs/loader.js:693:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/out/src/components/builder.js:8:18)
	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/out/src/components/builder.js:478:3)
	at Module._compile (internal/modules/cjs/loader.js:693:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/out/src/main.js:11:19)
	at Object.<anonymous> (/home/lblassel/.vscode/extensions/james-yu.latex-workshop-8.1.0/out/src/main.js:417:3)
	at Module._compile (internal/modules/cjs/loader.js:693:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
	at Module.load (internal/modules/cjs/loader.js:602:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
	at Function.Module._load (internal/modules/cjs/loader.js:533:3)
	at Function.define._installInterceptor.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:508:859)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:777:268)
	at Function.t.getExtensionPathIndex.then.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:176)
	at Module.require (internal/modules/cjs/loader.js:640:17)
	at require (internal/modules/cjs/helpers.js:20:18)
	at Function.i [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:31:639)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:60
	at I._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:168)
	at I._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:762:6)
	at I.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:758:868)
	at Generator.next (<anonymous>)
	at n (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:979)
	at new Promise (<anonymous>)
	at n (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:13:756)
	at Object.actualActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:758:570)
	at p._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:497:144)
	at define._activateExtensions.r.length.Promise.all.s.map.e (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:814)
	at Array.map (<anonymous>)
	at p._activateExtensions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:802)
	at p.activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:494:635)
	at I._activateByEvent (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:760:680)
	at define.$activateByEvent._readyToRunExtensions.wait.then.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:769:470)
webviewElement.ts:342 [Embedded Page] PDF 3a502bc97c8667397ee5ee3aaa8e0e75 [1.5 pdfTeX-1.40.18 / TeX] (PDF.js: 2.1.266)
notificationsAlerts.ts:40 Output PDF /home/lblassel/latex_workshop_test/latex.pdf is locked. Is it opened in other applications?
onDidNotificationChange @ notificationsAlerts.ts:40
webviewElement.ts:342 [Embedded Page] PDF 3a502bc97c8667397ee5ee3aaa8e0e75 [1.5 pdfTeX-1.40.18 / TeX] (PDF.js: 2.1.266)
webviewElement.ts:342 [Embedded Page] PDF f3ef62302c20583449c3b4a4ff130ed5 [1.5 pdfTeX-1.40.18 / TeX] (PDF.js: 2.1.266)
````

</details>

**Desktop [Required]:**
 - OS: **Ubuntu 16.04** (Linux x64 4.4.0-127-generic)
 - VS Code version: **1.37.1**
 - Extension version: **8.1.0**

**Are you using LaTeX Workshop with VS Code Remote?**

No

**Additional context**
I am using a docker container to compile, with the Docker option enabled in the extension.  
The image used is `blang/latex:ctanfull`

**Comment by praenubilus** [comment]
Having the same issue here. I am using Ubuntu 18.04 and docker container too. And I have noticed the generated PDF and auxiliary file will have a lock symbol in nautilus for a while(maybe 1-2 months). But it is working as expected. However, after latest update(8.1.0), the building will hang, maybe it is caused by locked PDF. And the PDF file will never be updated unless I: exit vscode, delete pdf and auxiliary file.

**Comment by praenubilus** [comment]
P.S. I tried several 8.x.x version, they all have this problem. Until I roll back to version 7.3.0, the problem goes away

**Comment by jlelong** [comment]
I think this is fixed by #1668.

**Comment by praenubilus** [comment]
Will this fix being included in next release? And when can I expect the next release being available?

**Comment by praenubilus** [comment]
I have updated to 8.1.1, still having the lock issue on Ubuntu+Docker. Works good on Mac. If I downgrade to 8.0.6, the problem goes away.
