### ISSUE TITLE
Writing \end would autocomplete with another \end

### ISSUE THREAD

**Issue by ttoommxx** [James-Yu/LaTeX-Workshop#3783]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: Chrome OS (Crostini - Debian 11)
- Visual Studio Code Version: 1.76.2
- LaTeX Workshop Version: 9.7.0
- TeX Distribution Version: TeX Live 2020

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
- I am using XXX whose version is YY.ZZ

## The Issue*
> _Please briefly describe the issue you come across._
-  When I write \end{theorem} in a \begin{theorem} environment, the extension would auto-complete to \end{theorem} <space> \end{theoren} as if the first end was a \begin
- 
- 

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. write \begin{theorem}
2. remove the auto-completed \end{theorem}
3. write \end{theorem} again
[Screen recording 2023-03-21 19.03.30.webm](https://user-images.githubusercontent.com/58073175/226714774-aa2ba366-b2b1-47c9-81a1-6306bb27a12e.webm)

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- no auto-completion upon re-writing \end{theorem}
- 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
<IT'S JUST EMPTY>
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
workbench.desktop.main.js:1882 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///usr/share/code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///home/ttoommxx/.vscode/extensions/james-yu.latex-workshop-9.7.0/syntax/TeX.tmLanguage.json
register @ workbench.desktop.main.js:1882
workbench.desktop.main.js:1882 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///usr/share/code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///home/ttoommxx/.vscode/extensions/james-yu.latex-workshop-9.7.0/syntax/LaTeX.tmLanguage.json
register @ workbench.desktop.main.js:1882
workbench.desktop.main.js:1882 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///usr/share/code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///home/ttoommxx/.vscode/extensions/james-yu.latex-workshop-9.7.0/syntax/Bibtex.tmLanguage.json
register @ workbench.desktop.main.js:1882
workbench.desktop.main.js:1882 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///usr/share/code/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///home/ttoommxx/.vscode/extensions/james-yu.latex-workshop-9.7.0/syntax/markdown-latex-combined.tmLanguage.json
register @ workbench.desktop.main.js:1882
workbench.desktop.main.js:1882 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///usr/share/code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///home/ttoommxx/.vscode/extensions/james-yu.latex-workshop-9.7.0/syntax/cpp-grammar-bailout.tmLanguage.json
register @ workbench.desktop.main.js:1882
workbench.desktop.main.js:615  INFO [perf] Render performance baseline is 92ms
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
```

## Anything Else?
> _Add any other context about the problem below._
-

**Comment by jlelong** [comment]
I cannot reproduce the issue.

**Comment by ttoommxx** [comment]
That's quite strange, I did try on my home workstation, which is Arch-based, and the problem persists. Did you have a look at the video I uploaded and reproduced that? Apparently that happens even without removing \end{theorem} but just writing a new \end{theorem} again.






On Tuesday, 21 March 2023 at 19:19:53 GMT, Jerome Lelong ***@***.***> wrote: 







I cannot reproduce the issue.

**Comment by ttoommxx** [comment]
> The issue only happens if you start typing `\end` with the cursor not aligned with the start of `\begin`. Note after typing the `{` in `\end{`, the lines is de-indented. This behaviour is really weird and I have really no idea what could cause this in the extension. I am really wondering if this might not be a VS Code issue.

Exactly, that's when it happens, write backslash, the environment get de-indented and then it autocompletes to \end.

**Comment by jlelong** [comment]
I think this is a VS Code issue. I have reported it https://github.com/microsoft/vscode/issues/178075

**Comment by ttoommxx** [comment]
Couldn't quite tell whether it was the extension or VScode itself, thanks for sorting that out for me! Shall I close the thread then?

**Comment by jlelong** [comment]
We can leave the issue open for now. I will take care of it.

**Comment by James-Yu** [comment]
It seems that somehow the issue was fixed on vscode side. I will close this issue for now.

https://github.com/James-Yu/LaTeX-Workshop/assets/4210342/b8cc8926-5701-4511-8dcf-462c63d24e97

**Comment by ian-h-chamberlain** [comment]
I'm still seeing this behavior with `\end{itemize}` on `v9.17.0` of the extension and VSCode `1.85.1`. The issue as described in #178075 seems different than what I'm seeing, but maybe I'm misunderstanding the original issue here... the completion of `\end` behaves as though it was completing `\begin`, in my case:

https://github.com/James-Yu/LaTeX-Workshop/assets/11131775/3c0107ce-1012-4964-969a-a941039e409d

Is the the same thing, or should I file a different issue to track this?

**Comment by jlelong** [comment]
With VS Code 1.85.1, I can reproduce https://github.com/microsoft/vscode/issues/178075 with all extensions disabled included LW

![Jan-04-2024 07-49-32](https://github.com/James-Yu/LaTeX-Workshop/assets/2910140/944ca860-9978-47c6-afcd-326e007d9649)

When activating LW

![Jan-04-2024 07-52-05](https://github.com/James-Yu/LaTeX-Workshop/assets/2910140/1a0466cd-c1b5-4de0-a6ca-8183c0829821)

**Comment by LinqLover** [comment]
@jlelong Sorry if I'm hijacking this issue, I'm not sure whether this would be the same issue or a new feature request: Could we also have automatic completion of `\end{theorem}` after typing `\begin{theorem`? Currently, I can either type `theorem` and press tab (but this only works for environments that have already existed during the last build) or start with `\begin{theorem` and write everything manually.

**Comment by James-Yu** [comment]
@LinqLover It's a different thing.
