### ISSUE TITLE
Math preview stop working after update to 9.9.0  version

### ISSUE THREAD

**Issue by IlyaGarazha** [James-Yu/LaTeX-Workshop#3869]
> _Please fill the following fields with a star (*) and provide as much related information as possible._

## Pre-checks*
> _Please change the following `[ ]` to `[x]` for confirmation._
- [x] The issue has not been reported in this repository.
- [x] The issue remains after disabling all other extensions and restarting Visual Studio Code.
- [x] The [FAQ](https://github.com/James-Yu/LaTeX-Workshop/wiki/FAQ) cannot address the issue.
- [x] The issue is not related to compiling a document, or the document can be successfully compiled in the OS terminal but not in Visual Studio Code with this extension.

## Environment*
> _Please write exact version numbers instead of descriptors such as `latest`._
- Operating System: [Ubuntu 22.04.2 LTS]
- Visual Studio Code Version: [1.77.3]
- LaTeX Workshop Version: [9.9.0]
- TeX Distribution Version: [TeX 3.141592653 (TeX Live 2022/dev/Debian) ]

> _Please list the environment and version number if you are using VSCodium, Snap or Flatpack versions of Visual Studio Code, and/or Visual Studio Code Remote Containers/SSH/WSL._
VS Code "About" contain:
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.19.0-41-generic snap
Sandboxed: No

## The Issue*
> _Please briefly describe the issue you come across._
-  MathPreview stop working. No symbols are visible in any document or any math equation.
- Firstly I reinstall LatexWorkshop and then reinstall VS Code completely. But MathPreview started to work only after downgrade to 9.8.2 LatexWorkshop version. I don't want to upgrade to 9.9.0 now because of importance of math preview for me.

### Reproduction Steps
> _Please list out the steps to reproduce your bug. Include relevant environmental variables or any other configuration._
1. 
2. 
3. 

### Expected Behavior
> _What were you expecting to see? Include any relevant examples or documentation links._
- 
- 

### LaTeX Workshop Output*
> _Please paste the whole log messages below, not parts of ones. The log should start with `New log placeholder %WS1% registered`._
```
[11:39:19][Logger] New log placeholder %WS1% registered for /home/ilya/Activities/Work/Python/Projects/Filter .
[11:39:19][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[11:39:19][Server] Creating LaTeX Workshop http and websocket server.
[11:39:19][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":46647} .
[11:39:19][Extension] Initializing LaTeX Workshop.
[11:39:19][Extension] Extension root: /home/ilya/.vscode/extensions/james-yu.latex-workshop-9.8.2
[11:39:19][Extension] $PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[11:39:19][Extension] $SHELL: /usr/bin/zsh
[11:39:19][Extension] $LANG: en_US.UTF-8
[11:39:19][Extension] $LC_ALL: undefined
[11:39:19][Extension] process.platform: linux
[11:39:19][Extension] process.arch: x64
[11:39:19][Extension] vscode.env.appName: Visual Studio Code
[11:39:19][Extension] vscode.env.remoteName: undefined
[11:39:19][Extension] vscode.env.uiKind: 1
[11:39:19][Extension] LaTeX Workshop initialized.
[11:39:19][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[11:39:19][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[11:39:19][Manager] Current workspace folders: ["file://%WS1%"]
[11:39:19][Manager] Found root file from active editor: %WS1%/1.tex
[11:39:19][Manager] Root file changed: from undefined to %WS1%/1.tex
[11:39:19][Manager] Start to find all dependencies.
[11:39:19][Manager] Root file languageId: latex
[11:39:19][Cacher][Watcher] Reset.
[11:39:19][Cacher] Adding %WS1%/1.tex .
[11:39:19][Cacher][Watcher] Watched %WS1%/1.tex with a new watcher on %WS1% .
[11:39:19][Cacher] Caching %WS1%/1.tex .
[11:39:19][Cacher] Updated inputs of %WS1%/1.tex .
[11:39:19][Server] valdOrigin is http://127.0.0.1:46647
[11:39:19][Viewer][Panel] Restoring at column 1 with state {"pdfFileUri":"file://%WS1%/1.pdf","scale":"auto","scrollMode":0,"sidebarView":0,"spreadMode":0,"scrollTop":0,"scrollLeft":0,"trim":0,"synctexEnabled":true,"autoReloadEnabled":true}.
[11:39:19][Preview][Math] Math preview panel: restored
[11:39:19][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:46647/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRmhvbWUlMkZpbHlhJTJGQWN0aXZpdGllcyUyRldvcmslMkZQeXRob24lMkZQcm9qZWN0cyUyRkZpbHRlciUyRjEucGRm .
[11:39:19][Cacher][Watcher] Watched %WS1%/1.pdf with a new watcher on %WS1% .
[11:39:19][DupLabel] Checking for duplicate labels: %WS1%/1.tex .
[11:39:19][Cacher] Updated elements of %WS1%/1.tex .
[11:39:19][Cacher] Updated bibs of %WS1%/1.tex .
[11:39:19][Cacher] Cached %WS1%/1.tex .
[11:39:19][Cacher] Parsing .fls %WS1%/1.fls .
[11:39:19][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1000.tfm .
[11:39:19][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1000.tfm with a new watcher on /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a .
[11:39:19][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1728.tfm .
[11:39:19][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1728.tfm .
[11:39:19][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/labx1728.tfm .
[11:39:19][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/labx1728.tfm .
[11:39:19][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1200.tfm .
[11:39:19][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1200.tfm .
[11:39:19][Cacher] Adding %WS1%/images/pend.png .
[11:39:19][Cacher][Watcher] Watched %WS1%/images/pend.png with a new watcher on %WS1%/images .
[11:39:19][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/pk/ljfour/lh/lh-t2a/larm1000.600pk .
[11:39:19][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/pk/ljfour/lh/lh-t2a/larm1000.600pk with a new watcher on /home/ilya/.texlive2021/texmf-var/fonts/pk/ljfour/lh/lh-t2a .
[11:39:19][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/pk/ljfour/lh/lh-t2a/labx1728.600pk .
[11:39:19][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/pk/ljfour/lh/lh-t2a/labx1728.600pk .
[11:39:19][Cacher] Found .aux %WS1%/1.tex from .fls %WS1%/1.fls , parsing.
[11:39:19][Cacher] Parsed .aux %WS1%/1.tex .
[11:39:19][Cacher] Parsed .fls %WS1%/1.fls .
[11:39:19][Structure] Structure force updated with 3 root sections for %WS1%/1.tex .
[11:39:20][Preview][Math] Math preview panel: initialized
[11:39:20][Viewer] Handle data type: open
[11:39:21][Server] Preview PDF file: file://%WS1%/1.pdf
[11:39:22][Viewer] Handle data type: loaded
[11:57:11][Structure] Structure updated with 3 root sections for %WS1%/1.tex .
[11:57:17][Commander] SHOWLOG command invoked: defaul
```

### Developer Tools Console
> _Please paste the whole log messages below, not parts of ones. This console logs can sometimes be very important in many cases. To access the log, click `Help` -> `Toggle Developer Tools` -> `Console`._
```
[Paste the log here. Do not remove the surrounding backquotes (`).]
```

## Anything Else?
> _Add any other context about the problem below._
This is log of 9.9.0 LatexWorkshop version, but MathPreview panel is empty (instead of 9.8.2 version with the same latex formula
![report_9_8_2](https://user-images.githubusercontent.com/9694293/235625657-7e36ee67-b6e6-43ca-aee8-cef0457c8c69.png)
![report_9_9_0](https://user-images.githubusercontent.com/9694293/235625669-602d2e59-5346-450a-a562-50297a1fb003.png)
)
```
[12:00:09][Logger] New log placeholder %WS1% registered for /home/ilya/Activities/Work/Python/Projects/Filter .
[12:00:09][Manager] Set $LATEXWORKSHOP_DOCKER_LATEX: ""
[12:00:09][Server] Creating LaTeX Workshop http and websocket server.
[12:00:09][Server] Server successfully started: {"address":"127.0.0.1","family":"IPv4","port":33941} .
[12:00:09][Extension] Initializing LaTeX Workshop.
[12:00:09][Extension] Extension root: /home/ilya/.vscode/extensions/james-yu.latex-workshop-9.9.0
[12:00:09][Extension] $PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[12:00:09][Extension] $SHELL: /usr/bin/zsh
[12:00:09][Extension] $LANG: en_US.UTF-8
[12:00:09][Extension] $LC_ALL: undefined
[12:00:09][Extension] process.platform: linux
[12:00:09][Extension] process.arch: x64
[12:00:09][Extension] vscode.env.appName: Visual Studio Code
[12:00:09][Extension] vscode.env.remoteName: undefined
[12:00:09][Extension] vscode.env.uiKind: 1
[12:00:09][Extension] LaTeX Workshop initialized.
[12:00:09][Format][Bib] Bibtex format config: {"tab":"  ","case":"lowercase","left":"{","right":"}","trailingComma":false,"sort":["key"],"alignOnEqual":true,"sortFields":false,"fieldsOrder":[],"firstEntries":["string","xdata"]}
[12:00:09][Extension] Trigger characters for intellisense of LaTeX documents: ["\\",",","{"]
[12:00:09][Manager] Current workspace folders: ["file://%WS1%"]
[12:00:09][Manager] Found root file from active editor: %WS1%/1.tex
[12:00:09][Manager] Root file changed: from undefined to %WS1%/1.tex
[12:00:09][Manager] Start to find all dependencies.
[12:00:09][Manager] Root file languageId: latex
[12:00:09][Cacher][Watcher] Reset.
[12:00:09][Cacher] Adding %WS1%/1.tex .
[12:00:09][Cacher][Watcher] Watched %WS1%/1.tex with a new watcher on %WS1% .
[12:00:09][Cacher] Caching %WS1%/1.tex .
[12:00:09][Cacher] Updated inputs of %WS1%/1.tex .
[12:00:09][Cacher] Parse LaTeX AST with fast-parse: %WS1%/1.tex .
[12:00:09][Server] valdOrigin is http://127.0.0.1:33941
[12:00:10][Viewer][Panel] Restoring at column 1 with state {"pdfFileUri":"file://%WS1%/1.pdf","scale":"auto","scrollMode":0,"sidebarView":0,"spreadMode":0,"scrollTop":0,"scrollLeft":0,"trim":0,"synctexEnabled":true,"autoReloadEnabled":true}.
[12:00:10][Preview][Math] Math preview panel: restored
[12:00:10][DupLabel] Checking for duplicate labels: %WS1%/1.tex .
[12:00:10][Cacher] Updated elements of %WS1%/1.tex .
[12:00:10][Cacher] Updated bibs of %WS1%/1.tex .
[12:00:10][Cacher] Cached %WS1%/1.tex .
[12:00:10][Structure][LaTeX] Building LaTeX structure from %WS1%/1.tex .
[12:00:10][Cacher] Parsing .fls %WS1%/1.fls .
[12:00:10][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1000.tfm .
[12:00:10][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1000.tfm with a new watcher on /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a .
[12:00:10][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1728.tfm .
[12:00:10][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1728.tfm .
[12:00:10][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/labx1728.tfm .
[12:00:10][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/labx1728.tfm .
[12:00:10][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1200.tfm .
[12:00:10][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/tfm/lh/lh-t2a/larm1200.tfm .
[12:00:10][Cacher] Adding %WS1%/images/pend.png .
[12:00:10][Cacher][Watcher] Watched %WS1%/images/pend.png with a new watcher on %WS1%/images .
[12:00:10][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/pk/ljfour/lh/lh-t2a/larm1000.600pk .
[12:00:10][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/pk/ljfour/lh/lh-t2a/larm1000.600pk with a new watcher on /home/ilya/.texlive2021/texmf-var/fonts/pk/ljfour/lh/lh-t2a .
[12:00:10][Cacher] Adding /home/ilya/.texlive2021/texmf-var/fonts/pk/ljfour/lh/lh-t2a/labx1728.600pk .
[12:00:10][Cacher][Watcher] Watched /home/ilya/.texlive2021/texmf-var/fonts/pk/ljfour/lh/lh-t2a/labx1728.600pk .
[12:00:10][Cacher] Found .aux %WS1%/1.tex from .fls %WS1%/1.fls , parsing.
[12:00:10][Cacher] Parsed .aux %WS1%/1.tex .
[12:00:10][Cacher] Parsed .fls %WS1%/1.fls .
[12:00:10][Structure] Structure force updated with 3 root sections for %WS1%/1.tex .
[12:00:10][Viewer][Panel] Internal PDF viewer at http://127.0.0.1:33941/viewer.html?file=pdf..ZmlsZSUzQSUyRiUyRiUyRmhvbWUlMkZpbHlhJTJGQWN0aXZpdGllcyUyRldvcmslMkZQeXRob24lMkZQcm9qZWN0cyUyRkZpbHRlciUyRjEucGRm .
[12:00:10][Cacher][Watcher] Watched %WS1%/1.pdf with a new watcher on %WS1% .
[12:00:10][Preview][Math] Parse LaTeX preamble AST.
[12:00:10][Preview][Math] Parsed 22 AST items.
[12:00:10][Preview][Math] Parse LaTeX preamble AST.
[12:00:10][Preview][Math] Parsed 22 AST items.
[12:00:11][Preview][Math] Math preview panel: initialized
[12:00:11][Preview][Math] Parse LaTeX preamble AST.
[12:00:11][Preview][Math] Parse LaTeX preamble AST.
[12:00:11][Preview][Math] Parsed 22 AST items.
[12:00:11][Preview][Math] Parsed 22 AST items.
[12:00:11][Viewer] Handle data type: open
[12:00:12][Server] Preview PDF file: file://%WS1%/1.pdf
[12:00:12][Preview][Math] Parse LaTeX preamble AST.
[12:00:12][Preview][Math] Parsed 22 AST items.
[12:00:14][Viewer] Handle data type: loaded
[12:00:15][Structure][LaTeX] Building LaTeX structure from %WS1%/1.tex .
[12:00:15][Structure][LaTeX] Parse active document LaTeX AST with fast-parse.
[12:00:42][Preview][Math] Parse LaTeX preamble AST.
[12:00:42][Preview][Math] Parsed 22 AST items.
[12:00:42][Preview][Math] Parse LaTeX preamble AST.
[12:00:42][Preview][Math] Parsed 22 AST items.
[12:00:42][Preview][Math] Parse LaTeX preamble AST.
[12:00:42][Preview][Math] Parsed 22 AST items.
```

**Comment by lijunkang12** [comment]
I confirm the same problem arises on my machine with the following environment:
Operating System: [MacOS 13.3]
Visual Studio Code Version: [1.77.3]
LaTeX Workshop Version: [9.9.0]
TeX Distribution Version: [TeX Live 2023]

**Comment by James-Yu** [comment]
I don't see a problem with the latest cc20baf8. This issue may be resolved by #3867 . See below:
<img width="799" alt="Screenshot 2023-05-03 at 13 31 48" src="https://user-images.githubusercontent.com/4210342/235838928-4dfe0704-cd9d-469b-bbb0-078233e6d2e6.png">

**Comment by lijunkang12** [comment]
The problem seems to persist in 9.10.0. Here is a minimal working example:
```LaTeX
\documentclass{article}
\def\subsectionautorefname{Subsection}
\begin{document}
\[
  a^2
\]
\end{document}
```
Math Preview stops working; and it works again if the second line (the one with \def) is commented.

**Comment by James-Yu** [comment]
> The problem seems to persist in 9.10.0. Here is a minimal working example:
> 
> ```
> \documentclass{article}
> \def\subsectionautorefname{Subsection}
> \begin{document}
> \[
>   a^2
> \]
> \end{document}
> ```
> 
> Math Preview stops working; and it works again if the second line (the one with \def) is commented.

This is a different issue. Resolved in df5c791.

**Comment by ZelnickB** [comment]
Can we reopen this issue? I am still encountering it (running LaTeX-Workshop v9.10.0, VS Code 1.78.0 on Darwin arm64). The math preview panel is broken *and* the preview-on-hover functionality is also not working. I'm getting this error in the DevTools console when I hover over math (no preview appears) and when I open the math preview panel:
```
  ERR Cannot read properties of undefined (reading 'replace'): TypeError: Cannot read properties of undefined (reading 'replace')
    at ~/.vscode/extensions/james-yu.latex-workshop-9.10.0/out/src/providers/preview/mathpreviewlib/newcommandfinder.js:108:43
    at Array.forEach (<anonymous>)
    at Function.findNewCommand (~/.vscode/extensions/james-yu.latex-workshop-9.10.0/out/src/providers/preview/mathpreviewlib/newcommandfinder.js:106:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Function.findProjectNewCommand (~/.vscode/extensions/james-yu.latex-workshop-9.10.0/out/src/providers/preview/mathpreviewlib/newcommandfinder.js:96:40)
    at HoverProvider.provideHover (~/.vscode/extensions/james-yu.latex-workshop-9.10.0/out/src/providers/hover.js:41:37)
    at m.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:42744)
```

**Comment by James-Yu** [comment]
Please open new.
