### ISSUE TITLE
Problems Window refers to a nonexistent file if the file path has special characters (space, etc.)

### ISSUE THREAD

**Issue by sloth3toe** [James-Yu/LaTeX-Workshop#784]
### Description

File path is not recognized in the PROBLEM window if there are spaces or special characters. Therefore, you can't click on a warning to get to the right line.

### Log messages
No log error / not applicable

### How to reproduce

1. Create a .tex file inside a folder whose path has a space for example. 
2. Intentionally add some kind of error, or some kind of warning (bad box or something).
3. Compile and look at the PROBLEMS window. 

### Expected behavior
The problems should show up in the PROBLEMS window. They should be clickable, and clicking them shows the line with the error/warning.

### Actual behavior
The problems will show up, but under a nonexistent file path, which gets cut off because of the special characters. Clicking on any problem will show an error notification popup saying "Unable to open...: File not found" with the truncated path.

**Comment by James-Yu** [comment]
It's mostly LaTeX's problem. If not, please provide  minimal workinh example.

**Comment by sloth3toe** [comment]
I'm unsure what would be a minimal working example here. Do you want a test file in a test folder? The only 2 requirements to reproduce the issue is that the file has to have some kind of compiling errors or warnings, and the path to the file has to have some spacing characters.

**Comment by philipstarkey** [comment]
I think this might be the same as what I reported in #786 (and is now fixed in the source)

**Comment by sloth3toe** [comment]
@philipstarkey, yes it is indeed the same problem. I'm glad your "version" of the same problem got chosen to be fixed! ;-)

**Comment by Lachimaus** [comment]
Hi, I'm new to VS Code. I installed the LW extension and this problem with special characters still persists. I have 1.28.2 VS Code version. I tried it with 1.25 version and the error message dissapears, however it still doesn't show me the line with the problem.
