### ISSUE TITLE
View PDF not working on windows

### ISSUE THREAD

**Issue by Michaelvll** [James-Yu/LaTeX-Workshop#941]
### Description

On windows, the view pdf does not work either in vscode tab or browser, since the last update on 11-03 [5.14.0]. A page called "PDF.js viewer" pop up with nothing shown (just a blank page).

### Log messages

<details>
<summary>LaTeX Workshop Output</summary>

[19:48:25] VIEW command invoked.
[19:48:25] Found root file from active editor: ***.tex
[19:48:25] Root file remains unchanged from: ***.tex.
[19:48:25] No PDF viewer connected for ***.pdf
[19:48:25] Serving PDF file at http://127.0.0.1:53043/viewer.html?file=/pdf:***.pdf
[19:48:25] Open PDF viewer for ***.pdf

</details>

<details>
<summary>Developer Tools Console</summary>

Nothing suspicious
</details>

### How to reproduce

1. Any tex file has the same problem

**Comment by Michaelvll** [comment]
Sorry but it seems still not working in version 5.14.1. :(
BTW, it still outputs that `No PDF viewer connected for ***.pdf`

**Comment by James-Yu** [comment]
Please provide a screenshot

**Comment by zhjc1124** [comment]
The same problem.
![image](https://user-images.githubusercontent.com/21313564/47952268-880ebd80-dfa7-11e8-8558-7648d9d5da25.png)

**Comment by wkindling** [comment]
I met this problem, too. And any PDF file cannot be viewed.

**Comment by nVentis** [comment]
Happens for me as well. Worked until some minutes ago, now just a white page is shown. When I choose "View in web browser", the developer console shows a file ("../build/pdf.js") could not be loaded, so maybe that's why subsequent calls to certain functions fail.

Maybe an online server supplying that fail (to the local server) is not reachable at the moment?

**Comment by James-Yu** [comment]
This was due to a mis-removed file in `pdfjs-dist` during publish, so it escaped the debug catch. The new version should be working fine.

**Comment by ganthern** [comment]
I'm having this problem right now, on Arch Linux with GNOME.

**Comment by 19majkel94** [comment]
@tamuratak Problem still exists 😞 

```
[11:03:09] VIEW command invoked.
[11:03:09] Found root file from active editor: c:\#Projekty\hardware-matcher\thesis\thesis.tex
[11:03:09] Root file remains unchanged from: c:\#Projekty\hardware-matcher\thesis\thesis.tex.
[11:03:09] No PDF viewer connected for c:\#Projekty\hardware-matcher\thesis\thesis.pdf
[11:03:09] Serving PDF file at http://127.0.0.1:55145/viewer.html?file=/pdf:c%253A%255C%2523Projekty%255Chardware-matcher%255Cthesis%255Cthesis.pdf
[11:03:09] Open PDF tab for c:\#Projekty\hardware-matcher\thesis\thesis.pdf
[11:03:11] Preview PDF file: c:/
```

![image](https://user-images.githubusercontent.com/10618781/47962721-4f132f00-e021-11e8-8b35-d89a4894916d.png)

The problem is with path - it worked ok for last 2 months, today it's broken. 
Changing folder name (without `#`) makes it work 😕

**Comment by ganthern** [comment]
@19majkel94 I also have a # in the path, 
@tamuratak yes, it's still happening on the current version. Here are some logs:

Output -> LaTeX Workshop
`
11:03:14] Initializing LaTeX Workshop.
[11:03:14] Creating LaTeX Workshop http and websocket server.
[11:03:14] LaTeX Workshop initialized.
[11:03:14] Found root file from active editor: /home/snip/#home/projects/latex/test/test.tex
[11:03:15] Root file changed from: undefined. Find all dependencies.
[11:03:15] Instatiating new file watcher for /home/snip/#home/projects/latex/test/test.tex
[11:03:15] Parsing /home/snip/#home/projects/latex/test/test.tex
[11:03:15] Server created on 127.0.0.1:36613
[11:03:15] Snippet data loaded.
[11:03:15] LaTeX Workshop version: 5.14.2
[11:03:16] Default data loaded.
[11:03:31] VIEW command invoked.
[11:03:31] Found root file from active editor: /home/snip/#home/projects/latex/test/test.tex
[11:03:31] Root file remains unchanged from: /home/snip/#home/projects/latex/test/test.tex.
[11:03:31] No PDF viewer connected for /home/snip/#home/projects/latex/test/test.pdf
[11:03:31] Serving PDF file at http://127.0.0.1:36613/viewer.html?file=/pdf:%252Fhome%252Fsnip%252F%2523home%252Fprojects%252Flatex%252Ftest%252Ftest.pdf
[11:03:31] Open PDF tab for /home/snip/#home/projects/latex/test/test.pdf
[11:03:31] VIEW command invoked.
[11:03:31] Found root file from active editor: /home/snip/#home/projects/latex/test/test.tex
[11:03:31] Root file remains unchanged from: /home/snip/#home/projects/latex/test/test.tex.
[11:03:31] No PDF viewer connected for /home/snip/#home/projects/latex/test/test.pdf
[11:03:31] Serving PDF file at http://127.0.0.1:36613/viewer.html?file=/pdf:%252Fhome%252Fsnip%252F%2523home%252Fprojects%252Flatex%252Ftest%252Ftest.pdf
[11:03:31] Open PDF tab for /home/snip/#home/projects/latex/test/test.pdf
[11:03:32] Preview PDF file: /home/snip/
[11:03:32] Preview PDF file: /home/snip/
`
last two lines seem truncated at the #, so I guess I have the same problem as @19majkel94. I'll just rename the directory for now.

Screenshot of the viewer after some time:
![latexworkshop](https://user-images.githubusercontent.com/29049728/47962849-2a1fbb80-e023-11e8-9e1b-b3043fce5aee.png)

**Comment by tamuratak** [comment]
@James-Yu 
How do you think?
